/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmatrix.controlador;

import java.io.File;
import java.io.RandomAccessFile;

/**
 *
 * @author matia
 */
public class ControladorArchivo extends javax.swing.JFrame {

    /**
     * Creates new form ControladorArchivo
     */
    public ControladorArchivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void guardar(java.awt.event.ActionEvent evt) {
        
        switch (this.jFileChooser1.showSaveDialog(null)) {
            
            case javax.swing.JFileChooser.APPROVE_OPTION:
                
                File archivo = this.jFileChooser1.getSelectedFile();
                
                break;
            
        }
        
    }
    
    public void cargar(java.awt.event.ActionEvent evt) {
        
        switch (this.jFileChooser1.showOpenDialog(null)) {
            
            case javax.swing.JFileChooser.APPROVE_OPTION:
                
                File archivo = this.jFileChooser1.getSelectedFile();
                
                try {
                
                    RandomAccessFile lectorArchivo = new RandomAccessFile(archivo, "r");
                    
                } catch (java.io.FileNotFoundException e) {
                    
                }
            
                break;
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
