/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmatrix;

import java.io.File;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.SwingUtilities;

import javax.swing.UnsupportedLookAndFeelException;
import java.io.FileNotFoundException;
import java.io.RandomAccessFile;

/**
 *
 * @author matia
 */
public class JMatrix extends javax.swing.JFrame {
    
    private ControladorLista primerControl;
    private ControladorLista segundoControl;
    private ControladorLista resultadoControl;
    
    private ControladorArchivo sistemaArchivos;
    
    private ArrayList<Matriz> matrices;
    private ArrayList<javax.swing.JList<String>> listas;
    private ArrayList<javax.swing.JTable> tablas;

    /**
     * Creates new form JMatrix
     */
    public JMatrix() {
        
        matrices = new ArrayList<Matriz>();
        
        initComponents();
        
        try {
            
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            
        }

        SwingUtilities.updateComponentTreeUI(this);
        
        this.listas = new ArrayList<javax.swing.JList<String>>();
        listas.add(this.primeraLista);
        listas.add(this.segundaLista);
        listas.add(this.resultadoLista);
        
        this.tablas = new ArrayList<javax.swing.JTable>();
        tablas.add(this.primeraMatriz);
        tablas.add(this.segundaMatriz);
        tablas.add(this.resultadoMatriz);
        
        primerControl = new ControladorLista(
                this.anchoPrimeraMatriz,
                this.largoPrimeraMatriz,
                this.primeraLista,
                this.primeraMatriz,
                this.listas,
                this.tablas,
                this.matrices
        );
        
        segundoControl = new ControladorLista(
                this.anchoSegundaMatriz,
                this.largoSegundaMatriz,
                this.segundaLista,
                this.segundaMatriz,
                this.listas,
                this.tablas,
                this.matrices
        );
        
        resultadoControl = new ControladorLista(
                null,
                null,
                this.resultadoLista,
                this.resultadoMatriz,
                this.listas,
                this.tablas,
                this.matrices
        );
        
        this.sistemaArchivos = new ControladorArchivo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        primeraMatriz = new javax.swing.JTable();
        nombrePrimeraMatriz = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        primeraLista = new javax.swing.JList<>();
        multiplicar = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        nombrePorPrimeraMatriz = new javax.swing.JLabel();
        okPrimeraMatriz = new javax.swing.JButton();
        anchoPrimeraMatriz = new javax.swing.JSpinner();
        largoPrimeraMatriz = new javax.swing.JSpinner();
        nombreAnchoPrimeraMatriz = new javax.swing.JLabel();
        nombreLargoPrimeraMatriz = new javax.swing.JLabel();
        agregarPrimeraMatriz = new javax.swing.JButton();
        escalonarPrimeraMatriz = new javax.swing.JButton();
        invertirPrimeraMatriz = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        primeraSalida = new javax.swing.JTextArea();
        nombreSalidaPrimeraMatriz = new javax.swing.JLabel();
        separadorPrimeraMatriz = new javax.swing.JSeparator();
        nombreSalidaSegundaMatriz = new javax.swing.JLabel();
        separadorSegundaMatriz = new javax.swing.JSeparator();
        nombrePorSegundaMatriz = new javax.swing.JLabel();
        okSegundaMatriz = new javax.swing.JButton();
        anchoSegundaMatriz = new javax.swing.JSpinner();
        largoSegundaMatriz = new javax.swing.JSpinner();
        nombreAnchoSegundaMatriz = new javax.swing.JLabel();
        nombreLargoSegundaMatriz = new javax.swing.JLabel();
        agregarSegundaMatriz = new javax.swing.JButton();
        escalonarSegundaMatriz = new javax.swing.JButton();
        invertirSegundaMatriz = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        segundaMatriz = new javax.swing.JTable();
        nombreSegundaMatriz = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        segundaLista = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        segundaSalida = new javax.swing.JTextArea();
        nombreIgualMatriz = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        resultadoMatriz = new javax.swing.JTable();
        nombreResultadoMatriz = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        resultadoLista = new javax.swing.JList<>();
        nombreSalidaResultadoMatriz = new javax.swing.JLabel();
        separadorTerceraMatriz = new javax.swing.JSeparator();
        escalonarResultadoMatriz = new javax.swing.JButton();
        invertirResultadoMatriz = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        resultadoSalida = new javax.swing.JTextArea();
        transponerPrimeraMatriz = new javax.swing.JButton();
        transponerSegundaMatriz = new javax.swing.JButton();
        transponerResultadoMatriz = new javax.swing.JButton();
        propiedadesResultadoMatriz = new javax.swing.JButton();
        propiedadesSegundaMatriz = new javax.swing.JButton();
        propiedadesPrimeraMatriz = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JMatrix");
        setResizable(false);

        primeraMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ) {

            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        });
        primeraMatriz.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                primeraMatrizPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(primeraMatriz);

        nombrePrimeraMatriz.setText("Primera matriz");

        primeraLista.setModel(new ListaModeloMatriz(matrices));
        primeraLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                primeraListaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(primeraLista);

        multiplicar.setText("*");
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });

        sumar.setText("+");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });

        restar.setText("-");
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });

        dividir.setText("/");
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });

        nombrePorPrimeraMatriz.setText("x");

        okPrimeraMatriz.setText("Ok");
        okPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPrimeraMatrizActionPerformed(evt);
            }
        });

        nombreAnchoPrimeraMatriz.setText("Ancho");

        nombreLargoPrimeraMatriz.setText("Largo");

        agregarPrimeraMatriz.setText("Agregar");
        agregarPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPrimeraMatrizActionPerformed(evt);
            }
        });

        escalonarPrimeraMatriz.setText("Escalonar");
        escalonarPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalonarPrimeraMatrizActionPerformed(evt);
            }
        });

        invertirPrimeraMatriz.setText("Invertir");
        invertirPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertirPrimeraMatrizActionPerformed(evt);
            }
        });

        primeraSalida.setColumns(20);
        primeraSalida.setRows(5);
        jScrollPane3.setViewportView(primeraSalida);

        nombreSalidaPrimeraMatriz.setText("Salida del proceso");

        nombreSalidaSegundaMatriz.setText("Salida del proceso");

        nombrePorSegundaMatriz.setText("x");

        okSegundaMatriz.setText("Ok");
        okSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okSegundaMatrizActionPerformed(evt);
            }
        });

        nombreAnchoSegundaMatriz.setText("Ancho");

        nombreLargoSegundaMatriz.setText("Largo");

        agregarSegundaMatriz.setText("Agregar");
        agregarSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSegundaMatrizActionPerformed(evt);
            }
        });

        escalonarSegundaMatriz.setText("Escalonar");
        escalonarSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalonarSegundaMatrizActionPerformed(evt);
            }
        });

        invertirSegundaMatriz.setText("Invertir");
        invertirSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertirSegundaMatrizActionPerformed(evt);
            }
        });

        segundaMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ) {

            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        });
        segundaMatriz.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                segundaMatrizPropertyChange(evt);
            }
        });
        jScrollPane4.setViewportView(segundaMatriz);
        if (segundaMatriz.getColumnModel().getColumnCount() > 0) {
            segundaMatriz.getColumnModel().getColumn(0).setResizable(false);
        }

        nombreSegundaMatriz.setText("Segunda matriz");

        segundaLista.setModel(new ListaModeloMatriz(matrices));
        segundaLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                segundaListaValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(segundaLista);

        segundaSalida.setColumns(20);
        segundaSalida.setRows(5);
        jScrollPane6.setViewportView(segundaSalida);

        nombreIgualMatriz.setText("=");

        resultadoMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ) {

            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        });
        jScrollPane7.setViewportView(resultadoMatriz);
        if (resultadoMatriz.getColumnModel().getColumnCount() > 0) {
            resultadoMatriz.getColumnModel().getColumn(0).setResizable(false);
        }

        nombreResultadoMatriz.setText("Resultado");

        resultadoLista.setModel(new ListaModeloMatriz(matrices));
        resultadoLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resultadoListaValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(resultadoLista);

        nombreSalidaResultadoMatriz.setText("Salida del proceso");

        escalonarResultadoMatriz.setText("Escalonar");
        escalonarResultadoMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalonarResultadoMatrizActionPerformed(evt);
            }
        });

        invertirResultadoMatriz.setText("Invertir");
        invertirResultadoMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertirResultadoMatrizActionPerformed(evt);
            }
        });

        resultadoSalida.setColumns(20);
        resultadoSalida.setRows(5);
        jScrollPane9.setViewportView(resultadoSalida);

        transponerPrimeraMatriz.setText("Transponer");
        transponerPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transponerPrimeraMatrizActionPerformed(evt);
            }
        });

        transponerSegundaMatriz.setText("Transponer");
        transponerSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transponerSegundaMatrizActionPerformed(evt);
            }
        });

        transponerResultadoMatriz.setText("Transponer");
        transponerResultadoMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transponerResultadoMatrizActionPerformed(evt);
            }
        });

        propiedadesResultadoMatriz.setText("?");

        propiedadesSegundaMatriz.setText("?");

        propiedadesPrimeraMatriz.setText("?");

        archivo.setText("Archivo");

        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmatrix/imagenes/Open Folder-16.png"))); // NOI18N
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        archivo.add(abrir);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmatrix/imagenes/Save as-16.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        archivo.add(guardar);

        jMenuBar1.add(archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrePrimeraMatriz)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(anchoPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombrePorPrimeraMatriz))
                                    .addComponent(nombreAnchoPrimeraMatriz))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLargoPrimeraMatriz)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(largoPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(okPrimeraMatriz))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(multiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(restar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(separadorPrimeraMatriz, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(escalonarPrimeraMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(invertirPrimeraMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(transponerPrimeraMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(propiedadesPrimeraMatriz))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreSalidaPrimeraMatriz)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreSegundaMatriz)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(anchoSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombrePorSegundaMatriz))
                                    .addComponent(nombreAnchoSegundaMatriz))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLargoSegundaMatriz)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(largoSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(okSegundaMatriz))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreIgualMatriz))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(separadorSegundaMatriz, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(transponerSegundaMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(invertirSegundaMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(escalonarSegundaMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(propiedadesSegundaMatriz))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreSalidaSegundaMatriz)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorTerceraMatriz)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(transponerResultadoMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(invertirResultadoMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(escalonarResultadoMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(propiedadesResultadoMatriz))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreSalidaResultadoMatriz)
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(nombreResultadoMatriz))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(nombreIgualMatriz))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombrePrimeraMatriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nombreAnchoPrimeraMatriz)
                                            .addComponent(nombreLargoPrimeraMatriz)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombrePorPrimeraMatriz)
                                    .addComponent(okPrimeraMatriz)
                                    .addComponent(anchoPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(largoPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregarPrimeraMatriz))
                                .addGap(14, 14, 14)
                                .addComponent(separadorPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreSalidaPrimeraMatriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(escalonarPrimeraMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(invertirPrimeraMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(transponerPrimeraMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(propiedadesPrimeraMatriz))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreSegundaMatriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nombreAnchoSegundaMatriz)
                                            .addComponent(nombreLargoSegundaMatriz)))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(multiplicar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dividir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sumar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(restar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombrePorSegundaMatriz)
                                    .addComponent(okSegundaMatriz)
                                    .addComponent(anchoSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(largoSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agregarSegundaMatriz))
                                .addGap(14, 14, 14)
                                .addComponent(separadorSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreSalidaSegundaMatriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(escalonarSegundaMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(invertirSegundaMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(transponerSegundaMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(propiedadesSegundaMatriz))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nombreResultadoMatriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane8)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addComponent(separadorTerceraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreSalidaResultadoMatriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(escalonarResultadoMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(invertirResultadoMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(transponerResultadoMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(propiedadesResultadoMatriz))
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        
        this.sistemaArchivos.guardar(evt);
        
    }//GEN-LAST:event_guardarActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        
        this.sistemaArchivos.cargar(evt);
        
    }//GEN-LAST:event_abrirActionPerformed

    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiplicarActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumarActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restarActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dividirActionPerformed

    private void escalonarPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalonarPrimeraMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escalonarPrimeraMatrizActionPerformed

    private void invertirPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertirPrimeraMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invertirPrimeraMatrizActionPerformed

    private void agregarPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPrimeraMatrizActionPerformed
        
        this.primerControl.agregar();
        
    }//GEN-LAST:event_agregarPrimeraMatrizActionPerformed

    private void agregarSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSegundaMatrizActionPerformed
        
        this.segundoControl.agregar();
        
    }//GEN-LAST:event_agregarSegundaMatrizActionPerformed

    private void escalonarSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalonarSegundaMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escalonarSegundaMatrizActionPerformed

    private void invertirSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertirSegundaMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invertirSegundaMatrizActionPerformed

    private void primeraListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_primeraListaValueChanged
        
        this.primerControl.seleccionar(evt);
        
    }//GEN-LAST:event_primeraListaValueChanged

    private void segundaListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_segundaListaValueChanged
        
        this.segundoControl.seleccionar(evt);
        
    }//GEN-LAST:event_segundaListaValueChanged

    private void resultadoListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resultadoListaValueChanged
        
        this.resultadoControl.seleccionar(evt);
        
    }//GEN-LAST:event_resultadoListaValueChanged

    private void escalonarResultadoMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalonarResultadoMatrizActionPerformed
        
    }//GEN-LAST:event_escalonarResultadoMatrizActionPerformed

    private void invertirResultadoMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertirResultadoMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invertirResultadoMatrizActionPerformed

    private void okPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPrimeraMatrizActionPerformed
        
        this.primerControl.ok(evt);
        
    }//GEN-LAST:event_okPrimeraMatrizActionPerformed

    private void okSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okSegundaMatrizActionPerformed
        
        this.segundoControl.ok(evt);
        
    }//GEN-LAST:event_okSegundaMatrizActionPerformed

    private void transponerPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transponerPrimeraMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transponerPrimeraMatrizActionPerformed

    private void transponerSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transponerSegundaMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transponerSegundaMatrizActionPerformed

    private void transponerResultadoMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transponerResultadoMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transponerResultadoMatrizActionPerformed

    private void primeraMatrizPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_primeraMatrizPropertyChange
        
        if (this.primerControl != null) {
            
            this.primerControl.propiedad(evt);
            
        }
        
    }//GEN-LAST:event_primeraMatrizPropertyChange

    private void segundaMatrizPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_segundaMatrizPropertyChange
        
        if (this.segundoControl != null) {
            
            this.segundoControl.propiedad(evt);
            
        }
        
    }//GEN-LAST:event_segundaMatrizPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMatrix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JButton agregarPrimeraMatriz;
    private javax.swing.JButton agregarSegundaMatriz;
    private javax.swing.JSpinner anchoPrimeraMatriz;
    private javax.swing.JSpinner anchoSegundaMatriz;
    private javax.swing.JMenu archivo;
    private javax.swing.JButton dividir;
    private javax.swing.JButton escalonarPrimeraMatriz;
    private javax.swing.JButton escalonarResultadoMatriz;
    private javax.swing.JButton escalonarSegundaMatriz;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JButton invertirPrimeraMatriz;
    private javax.swing.JButton invertirResultadoMatriz;
    private javax.swing.JButton invertirSegundaMatriz;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner largoPrimeraMatriz;
    private javax.swing.JSpinner largoSegundaMatriz;
    private javax.swing.JButton multiplicar;
    private javax.swing.JLabel nombreAnchoPrimeraMatriz;
    private javax.swing.JLabel nombreAnchoSegundaMatriz;
    private javax.swing.JLabel nombreIgualMatriz;
    private javax.swing.JLabel nombreLargoPrimeraMatriz;
    private javax.swing.JLabel nombreLargoSegundaMatriz;
    private javax.swing.JLabel nombrePorPrimeraMatriz;
    private javax.swing.JLabel nombrePorSegundaMatriz;
    private javax.swing.JLabel nombrePrimeraMatriz;
    private javax.swing.JLabel nombreResultadoMatriz;
    private javax.swing.JLabel nombreSalidaPrimeraMatriz;
    private javax.swing.JLabel nombreSalidaResultadoMatriz;
    private javax.swing.JLabel nombreSalidaSegundaMatriz;
    private javax.swing.JLabel nombreSegundaMatriz;
    private javax.swing.JButton okPrimeraMatriz;
    private javax.swing.JButton okSegundaMatriz;
    private javax.swing.JList<String> primeraLista;
    private javax.swing.JTable primeraMatriz;
    private javax.swing.JTextArea primeraSalida;
    private javax.swing.JButton propiedadesPrimeraMatriz;
    private javax.swing.JButton propiedadesResultadoMatriz;
    private javax.swing.JButton propiedadesSegundaMatriz;
    private javax.swing.JButton restar;
    private javax.swing.JList<String> resultadoLista;
    private javax.swing.JTable resultadoMatriz;
    private javax.swing.JTextArea resultadoSalida;
    private javax.swing.JList<String> segundaLista;
    private javax.swing.JTable segundaMatriz;
    private javax.swing.JTextArea segundaSalida;
    private javax.swing.JSeparator separadorPrimeraMatriz;
    private javax.swing.JSeparator separadorSegundaMatriz;
    private javax.swing.JSeparator separadorTerceraMatriz;
    private javax.swing.JButton sumar;
    private javax.swing.JButton transponerPrimeraMatriz;
    private javax.swing.JButton transponerResultadoMatriz;
    private javax.swing.JButton transponerSegundaMatriz;
    // End of variables declaration//GEN-END:variables
}
