/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jmatrix;

import java.io.File;
import java.util.ArrayList;
import javax.swing.UIManager;
import javax.swing.SwingUtilities;

import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author matia
 */
public class JMatrix extends javax.swing.JFrame {
    
    private ArrayList<Matriz> matrices;

    /**
     * Creates new form JMatrix
     */
    public JMatrix() {
        
        matrices = new ArrayList<Matriz>();
        
        initComponents();
        
        try {
            
            java.io.RandomAccessFile archivo = new java.io.RandomAccessFile("test.txt", "rw");
            
            Matriz mat = new Matriz(archivo);
            
            System.out.println(mat);
            
        } catch (java.io.FileNotFoundException e) {
            
        }
        
        try {
            
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            
        }

        SwingUtilities.updateComponentTreeUI(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        primeraMatriz = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        primeraLista = new javax.swing.JList<>();
        multiplicar = new javax.swing.JButton();
        sumar = new javax.swing.JButton();
        restar = new javax.swing.JButton();
        dividir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        okPrimeraMatriz = new javax.swing.JButton();
        anchoPrimeraMatriz = new javax.swing.JSpinner();
        largoPrimeraMatriz = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        agregarPrimeraMatriz = new javax.swing.JButton();
        escalonarPrimeraMatriz = new javax.swing.JButton();
        invertirPrimeraMatriz = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        primeraSalida = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        okSegundaMatriz = new javax.swing.JButton();
        anchoSegundaMatriz = new javax.swing.JSpinner();
        largoSegundaMatriz = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        agregarSegundaMatriz = new javax.swing.JButton();
        escalonarSegundaMatriz = new javax.swing.JButton();
        invertirSegundaMatriz = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        segundaMatriz = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        segundaLista = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        segundaSalida = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        resultadoMatriz = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        resultadoLista = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        escalonarResultadoMatriz = new javax.swing.JButton();
        invertirResultadoMatriz = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        resultadoSalida = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();

        jLabel6.setText("Ancho");

        jButton2.setText("Agregar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JMatrix");
        setResizable(false);

        primeraMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ) {

            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        });
        jScrollPane2.setViewportView(primeraMatriz);

        jLabel1.setText("Primera matriz");

        primeraLista.setModel(new ListaModeloMatriz(matrices));
        primeraLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                primeraListaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(primeraLista);

        multiplicar.setText("*");
        multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicarActionPerformed(evt);
            }
        });

        sumar.setText("+");
        sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumarActionPerformed(evt);
            }
        });

        restar.setText("-");
        restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restarActionPerformed(evt);
            }
        });

        dividir.setText("/");
        dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividirActionPerformed(evt);
            }
        });

        jLabel3.setText("x");

        okPrimeraMatriz.setText("Ok");
        okPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okPrimeraMatrizActionPerformed(evt);
            }
        });

        jLabel4.setText("Ancho");

        jLabel8.setText("Largo");

        agregarPrimeraMatriz.setText("Agregar");
        agregarPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPrimeraMatrizActionPerformed(evt);
            }
        });

        escalonarPrimeraMatriz.setText("Escalonar");
        escalonarPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalonarPrimeraMatrizActionPerformed(evt);
            }
        });

        invertirPrimeraMatriz.setText("Invertir");
        invertirPrimeraMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertirPrimeraMatrizActionPerformed(evt);
            }
        });

        primeraSalida.setColumns(20);
        primeraSalida.setRows(5);
        jScrollPane3.setViewportView(primeraSalida);

        jLabel2.setText("Salida del proceso");

        jLabel5.setText("Salida del proceso");

        jLabel7.setText("x");

        okSegundaMatriz.setText("Ok");
        okSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okSegundaMatrizActionPerformed(evt);
            }
        });

        jLabel9.setText("Ancho");

        jLabel10.setText("Largo");

        agregarSegundaMatriz.setText("Agregar");
        agregarSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarSegundaMatrizActionPerformed(evt);
            }
        });

        escalonarSegundaMatriz.setText("Escalonar");
        escalonarSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalonarSegundaMatrizActionPerformed(evt);
            }
        });

        invertirSegundaMatriz.setText("Invertir");
        invertirSegundaMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertirSegundaMatrizActionPerformed(evt);
            }
        });

        segundaMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ) {

            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        });
        jScrollPane4.setViewportView(segundaMatriz);
        if (segundaMatriz.getColumnModel().getColumnCount() > 0) {
            segundaMatriz.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel11.setText("Segunda matriz");

        segundaLista.setModel(new ListaModeloMatriz(matrices));
        segundaLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                segundaListaValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(segundaLista);

        segundaSalida.setColumns(20);
        segundaSalida.setRows(5);
        jScrollPane6.setViewportView(segundaSalida);

        jLabel12.setText("=");

        resultadoMatriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {}
        ) {

            public Class getColumnClass(int columnIndex) {
                return java.lang.Double.class;
            }
        });
        jScrollPane7.setViewportView(resultadoMatriz);
        if (resultadoMatriz.getColumnModel().getColumnCount() > 0) {
            resultadoMatriz.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel15.setText("Resultado");

        resultadoLista.setModel(new ListaModeloMatriz(matrices));
        resultadoLista.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                resultadoListaValueChanged(evt);
            }
        });
        jScrollPane8.setViewportView(resultadoLista);

        jLabel13.setText("Salida del proceso");

        escalonarResultadoMatriz.setText("Escalonar");
        escalonarResultadoMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalonarResultadoMatrizActionPerformed(evt);
            }
        });

        invertirResultadoMatriz.setText("Invertir");
        invertirResultadoMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertirResultadoMatrizActionPerformed(evt);
            }
        });

        resultadoSalida.setColumns(20);
        resultadoSalida.setRows(5);
        jScrollPane9.setViewportView(resultadoSalida);

        archivo.setText("Archivo");

        abrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmatrix/imagenes/Open Folder-16.png"))); // NOI18N
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        archivo.add(abrir);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jmatrix/imagenes/Save as-16.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        archivo.add(guardar);

        jMenuBar1.add(archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(multiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(restar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(anchoPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(largoPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(okPrimeraMatriz))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(escalonarPrimeraMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invertirPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(anchoSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(largoSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(okSegundaMatriz))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(escalonarSegundaMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invertirSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(escalonarResultadoMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(invertirResultadoMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(multiplicar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dividir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sumar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(restar)))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(okPrimeraMatriz)
                            .addComponent(anchoPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(largoPrimeraMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarPrimeraMatriz))
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(escalonarPrimeraMatriz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invertirPrimeraMatriz))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(79, 79, 79)
                                                .addComponent(jLabel12)))
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(okSegundaMatriz)
                            .addComponent(anchoSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(largoSegundaMatriz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarSegundaMatriz))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(escalonarSegundaMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(invertirSegundaMatriz))
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(escalonarResultadoMatriz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(invertirResultadoMatriz))
                                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        
        switch (this.jFileChooser2.showSaveDialog(null)) {
            
            case javax.swing.JFileChooser.APPROVE_OPTION:
                
                File archivo = this.jFileChooser1.getSelectedFile();
                
                break;
            
        }
        
    }//GEN-LAST:event_guardarActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        
        switch (this.jFileChooser1.showOpenDialog(null)) {
            
            case javax.swing.JFileChooser.APPROVE_OPTION:
                
                File archivo = this.jFileChooser1.getSelectedFile();
            
                break;
            
        }
        
    }//GEN-LAST:event_abrirActionPerformed
    
    public void actualizarListas() {
        
        ListaModeloMatriz modelo = new ListaModeloMatriz(matrices);
        
        primeraLista.setModel(modelo);
        segundaLista.setModel(modelo);
        resultadoLista.setModel(modelo);
        
    }
    
    private void multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiplicarActionPerformed

    private void sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumarActionPerformed

    private void restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restarActionPerformed

    private void dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dividirActionPerformed

    private void escalonarPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalonarPrimeraMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escalonarPrimeraMatrizActionPerformed

    private void invertirPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertirPrimeraMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invertirPrimeraMatrizActionPerformed

    private void agregarPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPrimeraMatrizActionPerformed
        
        int ancho = (Integer) anchoPrimeraMatriz.getValue();
        int largo = (Integer) largoPrimeraMatriz.getValue();
        
        matrices.add(new Matriz(ancho, largo));
        
        actualizarListas();
        
    }//GEN-LAST:event_agregarPrimeraMatrizActionPerformed

    private void agregarSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarSegundaMatrizActionPerformed
        
        int ancho = (Integer) anchoSegundaMatriz.getValue();
        int largo = (Integer) largoSegundaMatriz.getValue();
        
        matrices.add(new Matriz(ancho, largo));
        
        actualizarListas();
        
    }//GEN-LAST:event_agregarSegundaMatrizActionPerformed

    private void escalonarSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalonarSegundaMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escalonarSegundaMatrizActionPerformed

    private void invertirSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertirSegundaMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invertirSegundaMatrizActionPerformed

    private void primeraListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_primeraListaValueChanged
        
        if (evt.getValueIsAdjusting()) {
            
            Matriz matriz = matrices.get(evt.getFirstIndex());
            
            if (matriz != null) {
                
                matriz.insertar(primeraMatriz);
                
            }
            
        }
        
    }//GEN-LAST:event_primeraListaValueChanged

    private void segundaListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_segundaListaValueChanged
        
        if (evt.getValueIsAdjusting()) {
            
            Matriz matriz = matrices.get(evt.getFirstIndex());
            
            if (matriz != null) {
                
                matriz.insertar(segundaMatriz);
                
            }
            
        }
        
    }//GEN-LAST:event_segundaListaValueChanged

    private void resultadoListaValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_resultadoListaValueChanged
        
        if (evt.getValueIsAdjusting()) {
            
            Matriz matriz = matrices.get(evt.getFirstIndex());
            
            if (matriz != null) {
                
                matriz.insertar(resultadoMatriz);
                
            }
            
        }
        
    }//GEN-LAST:event_resultadoListaValueChanged

    private void escalonarResultadoMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalonarResultadoMatrizActionPerformed
        
    }//GEN-LAST:event_escalonarResultadoMatrizActionPerformed

    private void invertirResultadoMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertirResultadoMatrizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_invertirResultadoMatrizActionPerformed

    private void okPrimeraMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okPrimeraMatrizActionPerformed
        
        int ancho = (Integer) anchoPrimeraMatriz.getValue();
        int largo = (Integer) largoPrimeraMatriz.getValue();
        
        int indice = primeraLista.getSelectedIndex();
        
        Matriz matriz = new Matriz(ancho, largo);
        matriz.insertar(primeraMatriz);
        
        if (segundaLista.getSelectedIndex() == indice){
            
            matriz.insertar(segundaMatriz);
            
        }
        
        if (resultadoLista.getSelectedIndex() == indice){
            
            matriz.insertar(resultadoMatriz);
            
        }
        
        matrices.set(indice, matriz);
        actualizarListas();
        
    }//GEN-LAST:event_okPrimeraMatrizActionPerformed

    private void okSegundaMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okSegundaMatrizActionPerformed
        
        int ancho = (Integer) anchoSegundaMatriz.getValue();
        int largo = (Integer) largoSegundaMatriz.getValue();
        
        int indice = segundaLista.getSelectedIndex();
        
        Matriz matriz = new Matriz(ancho, largo);
        matriz.insertar(segundaMatriz);
        
        if (primeraLista.getSelectedIndex() == indice){
            
            matriz.insertar(primeraMatriz);
            
        }
        
        if (resultadoLista.getSelectedIndex() == indice){
            
            matriz.insertar(resultadoMatriz);
            
        }
        
        matrices.set(indice, matriz);
        actualizarListas();
        
    }//GEN-LAST:event_okSegundaMatrizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMatrix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMatrix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JButton agregarPrimeraMatriz;
    private javax.swing.JButton agregarSegundaMatriz;
    private javax.swing.JSpinner anchoPrimeraMatriz;
    private javax.swing.JSpinner anchoSegundaMatriz;
    private javax.swing.JMenu archivo;
    private javax.swing.JButton dividir;
    private javax.swing.JButton escalonarPrimeraMatriz;
    private javax.swing.JButton escalonarResultadoMatriz;
    private javax.swing.JButton escalonarSegundaMatriz;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JButton invertirPrimeraMatriz;
    private javax.swing.JButton invertirResultadoMatriz;
    private javax.swing.JButton invertirSegundaMatriz;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner largoPrimeraMatriz;
    private javax.swing.JSpinner largoSegundaMatriz;
    private javax.swing.JButton multiplicar;
    private javax.swing.JButton okPrimeraMatriz;
    private javax.swing.JButton okSegundaMatriz;
    private javax.swing.JList<String> primeraLista;
    private javax.swing.JTable primeraMatriz;
    private javax.swing.JTextArea primeraSalida;
    private javax.swing.JButton restar;
    private javax.swing.JList<String> resultadoLista;
    private javax.swing.JTable resultadoMatriz;
    private javax.swing.JTextArea resultadoSalida;
    private javax.swing.JList<String> segundaLista;
    private javax.swing.JTable segundaMatriz;
    private javax.swing.JTextArea segundaSalida;
    private javax.swing.JButton sumar;
    // End of variables declaration//GEN-END:variables
}
